################################################################################
# These macros are used by makefiles and argument files.
# When a space is included in the path and quotes (") cannot be used,
# a _ESCAPE version of the macro is added that escapes the space with backslash (\).
################################################################################

export GNU_Make_Install_DirEnv=$(CWInstallLocationEnv)/gnu/bin
export DSC_ToolsDirEnv=$(CWInstallLocationEnv)/MCU/DSP56800x_EABI_Tools/command_line_tools
export ProjDirPath=D:/Ani/Ani/Tesis/Firmware/Test/Prueba_PWM1
export CWInstallLocationEnv=D:/Freescale/CW MCU v10.6
export MCUToolsBaseDirEnv=$(CWInstallLocationEnv)/MCU
