/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : PWM_Timer.c
**     Project     : Prueba_PWM1
**     Processor   : MC56F8006_48_LQFP
**     Component   : Init_PWM
**     Version     : Component 01.295, Driver 01.23, CPU db: 3.00.209
**     Compiler    : CodeWarrior DSP C Compiler
**     Date/Time   : 2014-08-26, 08:51, # CodeGen: 11
**     Abstract    :
**         This "Init_PWM" Peripheral Inspector implements the
**         Puls Width Modulator module (PWM), basic initialization
**         and settings.
**     Settings    :
**         PWM module                  : PWM_Timer
**
**         Clock setting
**             PWM prescaler           : 1
**             Counter modulo          : 960
**             Dead time value         : 0
**             Reload frequency        : 1
**             PWM frequency           : 50 kHz
**             PWM period              : 20 us
**             PWM deadtime            : 0 us
**
**         Interrupts
**             Reload interrupt        : Disabled
**
**             Fault 0 interrupt       : Disabled
**             Fault 1 interrupt       : Disabled
**             Fault 2 interrupt       : Disabled
**             Fault 3 interrupt       : Disabled
**
**         HW acceleration             : Disabled
**
**         Correction
**             Method                  : Manual correction or no correction
**             Internal current ctrl.0 : Top
**             Internal current ctrl.1 : Top
**             Internal current ctrl.2 : Top
**
**         Channel settings
**             Alignment               : Center-aligned mode
**             Channels 0-1
**               Mode of PWM           : Independent
**               Phase shift PWM.      : Disabled
**               Top output polarity   : Positive
**               Bottom output polar.  : Positive
**             Channels 2-3
**               Mode of PWM channels  : Independent
**               Phase shift PWM.      : Disabled
**               Top output polarity   : Positive
**               Bottom output polar.  : Positive
**             Channels 4-5
**               Mode of PWM channels  : Independent
**               Phase shift PWM.      : Disabled
**               Top output polarity   : Positive
**               Bottom output polar.  : Positive
**
**         Enabled in wait mode        : no
**         Enabled in EnOnCE mode      : yes
**         Write protect               : no
**         Output pads                 : Disabled
**         Half cycle reload           : no
**
**         Channel 0
**             PWM Pin                 : GPIOA0_PWM0
**             Enable software control : yes
**             Channel masked          : no
**
**         Channel 3
**             PWM Pin                 : GPIOA3_PWM3_TXD_EXTAL
**             Enable software control : no
**             Channel masked          : no
**         Fault 0
**             clearing mode           : Manual
**             fault polarity          : Positive
**             glitch stretch          : Disabled
**         Fault 1
**             clearing mode           : Manual
**             fault polarity          : Positive
**             glitch stretch          : Disabled
**         Fault 2
**             clearing mode           : Manual
**             fault polarity          : Positive
**             glitch stretch          : Disabled
**         Fault 3
**             clearing mode           : Manual
**             fault polarity          : Positive
**             glitch stretch          : Disabled
**
**         Synchronization
**             output                  : Disabled
**             windowed input          : Disabled
**
**         Initialization
**             Call Init method        : yes
**             Enable peripheral clock : yes
**             Load values after init  : yes
**             Enable PWM generator    : yes
**
**     Contents    :
**         Init - void PWM_Timer_Init(void);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file PWM_Timer.c
** @version 01.23
** @brief
**         This "Init_PWM" Peripheral Inspector implements the
**         Puls Width Modulator module (PWM), basic initialization
**         and settings.
*/         
/*!
**  @addtogroup PWM_Timer_module PWM_Timer module documentation
**  @{
*/         

/* MODULE PWM_Timer. */

#include "PWM_Timer.h"

/*
** ===================================================================
**     Method      :  PWM_Timer_Init (component Init_PWM)
**     Description :
**         Peripheral Initialization Beans provide a low-level
**         hardware approach to initialize registers of the
**         peripheral module. They are intended for experienced
**         users.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void PWM_Timer_Init(void)
{
  /* PWM_CTRL: LDFQ=0,HALF=0,IPOL2=0,IPOL1=0,IPOL0=0,PRSC=0,PWMRIE=0,PWMF=0,??=0,??=0,LDOK=0,PWMEN=0 */
  setReg16(PWM_CTRL, 0x00U);            
  /* PWM_FCTRL: ??=0,??=0,??=0,??=0,FPOL3=0,FPOL2=0,FPOL1=0,FPOL0=0,FIE3=0,FMODE3=0,FIE2=0,FMODE2=0,FIE1=0,FMODE1=0,FIE0=0,FMODE0=0 */
  setReg16(PWM_FCTRL, 0x00U);           
  /* PWM_CMOD: ??=0,PWMCM=0x03C0 */
  setReg16(PWM_CMOD, 0x03C0U);          
  /* PWM_VAL0: PMVAL=0xA0 */
  setReg16(PWM_VAL0, 0xA0U);            
  /* PWM_VAL1: PMVAL=0 */
  setReg16(PWM_VAL1, 0x00U);            
  /* PWM_VAL2: PMVAL=0 */
  setReg16(PWM_VAL2, 0x00U);            
  /* PWM_VAL3: PMVAL=0xA0 */
  setReg16(PWM_VAL3, 0xA0U);            
  /* PWM_VAL4: PMVAL=0 */
  setReg16(PWM_VAL4, 0x00U);            
  /* PWM_VAL5: PMVAL=0 */
  setReg16(PWM_VAL5, 0x00U);            
  /* PWM_DMAP1: DISMAP_15_0=0 */
  setReg16(PWM_DMAP1, 0x00U);           
  /* PWM_DMAP2: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,DISMAP_23_16=0 */
  setReg16(PWM_DMAP2, 0x00U);           
  /* PWM_DTIM0: ??=0,??=0,??=0,??=0,PWMDT0=0 */
  setReg16(PWM_DTIM0, 0x00U);           
  /* PWM_DTIM1: ??=0,??=0,??=0,??=0,PWMDT1=0 */
  setReg16(PWM_DTIM1, 0x00U);           
  /* PWM_SYNC: SYNC_OUT_EN=0,SYNC_WINDOW=0 */
  setReg16(PWM_SYNC, 0x00U);            
  /* PWM_CCTRL: ENHA=0,nBX=0,MSK5=0,MSK4=0,MSK3=0,MSK2=0,MSK1=0,MSK0=0,??=0,??=0,VLMODE=0,??=0,SWP45=0,SWP23=0,SWP01=0 */
  setReg16(PWM_CCTRL, 0x00U);           
  /* PWM_OUT: PAD_EN=0,??=0,OUTCTL5=0,OUTCTL4=1,OUTCTL3=0,OUTCTL2=0,OUTCTL1=0,OUTCTL0=1,??=0,??=0,OUT5=0,OUT4=1,OUT3=0,OUT2=0,OUT1=0,OUT0=1 */
  setReg16(PWM_OUT, 0x1111U);           
  /* PWM_ICCTRL: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,PEC2=0,PEC1=0,PEC0=0,ICC2=0,ICC1=0,ICC0=0 */
  setReg16(PWM_ICCTRL, 0x00U);          
  /* PWM_SCTRL: ??=0,??=0,CINV5=0,CINV4=0,CINV3=0,CINV2=0,CINV1=0,CINV0=0,??=0,SRC2=0,??=0,SRC1=0,??=0,SRC0=0 */
  setReg16(PWM_SCTRL, 0x00U);           
  /* PWM_FFILT0: GSTR0=0,??=0,??=0,??=0,??=0,FILT0_CNT=0,FILT0_PER=0 */
  setReg16(PWM_FFILT0, 0x00U);          
  /* PWM_FFILT1: GSTR1=0,??=0,??=0,??=0,??=0,FILT1_CNT=0,FILT1_PER=0 */
  setReg16(PWM_FFILT1, 0x00U);          
  /* PWM_FFILT2: GSTR2=0,??=0,??=0,??=0,??=0,FILT2_CNT=0,FILT2_PER=0 */
  setReg16(PWM_FFILT2, 0x00U);          
  /* PWM_FFILT3: GSTR3=0,??=0,??=0,??=0,??=0,FILT3_CNT=0,FILT3_PER=0 */
  setReg16(PWM_FFILT3, 0x00U);          
  /* PWM_CNFG: ??=0,DBG_EN=1,WAIT_EN=0,EDG=0,??=0,TOPNEG45=0,TOPNEG23=0,TOPNEG01=0,??=0,BOTNEG45=0,BOTNEG23=0,BOTNEG01=0,INDEP45=1,INDEP23=1,INDEP01=1,WP=0 */
  setReg16(PWM_CNFG, 0x400EU);          
  /* PWM_FLTACK: FPIN3=0,FFLAG3=0,FPIN2=0,FFLAG2=0,FPIN1=0,FFLAG1=0,FPIN0=0,FFLAG0=0,??=0,FTACK3=1,??=0,FTACK2=1,??=0,FTACK1=1,??=0,FTACK0=1 */
  setReg16(PWM_FLTACK, 0x55U);         /* clear fault flags */ 
  /* PWM_FCTRL: ??=0,??=0,??=0,??=0,FPOL3=0,FPOL2=0,FPOL1=0,FPOL0=0,FIE3=0,FMODE3=0,FIE2=0,FMODE2=0,FIE1=0,FMODE1=0,FIE0=0,FMODE0=0 */
  setReg16(PWM_FCTRL, 0x00U);           
  /* PWM_CTRL: LDOK=1 */
  setReg16Bits(PWM_CTRL, 0x02U);       /* set LDOK bit */ 
  /* PWM_CTRL: PWMEN=1 */
  setReg16Bits(PWM_CTRL, 0x01U);       /* set PWMEN bit */ 
  /* PWM_CTRL: PWMF=0 */
  clrReg16Bits(PWM_CTRL, 0x10U);       /* clear PWMF flag */ 
}

/* END PWM_Timer. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
