/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : LED_Act.h
**     Project     : Cliente_DSP_SCI_GPIO_Timer_V2.1
**     Processor   : MC56F8006_48_LQFP
**     Component   : DSC_LED
**     Version     : Component 01.000, Driver 01.06, CPU db: 3.00.209
**     Compiler    : CodeWarrior DSP C Compiler
**     Date/Time   : 2015-12-19, 10:51, # CodeGen: 0
**     Abstract    :
**          This bean provide methods for driving of LED device.
**          Methods On, Off, Set and Toggle (or only initialization code)
**          could be used to drive it. Output value, defined by Init.
**          value property, is used for initialization implicitly.
**          It is not necessary to use any method explicitly in start up.
**          Method Status return current status of the LED device.
**          LED drivers without output inverter are supported
**          via Inverted value property.
**     Settings    :
**          Output PIN                                     :GPIOA4_PWM4_FAULT1_SDA_TIN2
**          Initialize Value                               :Off
**          Inverted Value                                 :no
**     Contents    :
**         On         - void LED_Act_On(void);
**         Off        - void LED_Act_Off(void);
**         Toggle     - void LED_Act_Toggle(void);
**         Set        - void LED_Act_Set(bool Output);
**         Status     - bool LED_Act_Status(void);
**         ConnectPin - void LED_Act_ConnectPin(void);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file LED_Act.h
** @version 01.06
** @brief
**          This bean provide methods for driving of LED device.
**          Methods On, Off, Set and Toggle (or only initialization code)
**          could be used to drive it. Output value, defined by Init.
**          value property, is used for initialization implicitly.
**          It is not necessary to use any method explicitly in start up.
**          Method Status return current status of the LED device.
**          LED drivers without output inverter are supported
**          via Inverted value property.
*/         
/*!
**  @addtogroup LED_Act_module LED_Act module documentation
**  @{
*/         

#ifndef __LED_Act
#define __LED_Act

/* MODULE LED_Act. */

/*Include shared modules, which are used for whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited components */
#include "Inhr1.h"

#include "Cpu.h"


#define LED_Act_On() Inhr1_SetVal()
/*
** ===================================================================
**     Method      :  LED_Act_On (component DSC_LED)
**     Description :
**         Switch ON the LED device
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define LED_Act_Off() Inhr1_ClrVal()
/*
** ===================================================================
**     Method      :  LED_Act_Off (component DSC_LED)
**     Description :
**         Switch OFF the LED device
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define LED_Act_Toggle() Inhr1_NegVal()
/*
** ===================================================================
**     Method      :  LED_Act_Toggle (component DSC_LED)
**     Description :
**         Toggle the LED device value
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define LED_Act_Set(Output) Inhr1_PutVal(Output)
/*
** ===================================================================
**     Method      :  LED_Act_Set (component DSC_LED)
**     Description :
**         Put the specified value to the LED
**     Parameters  :
**         NAME            - DESCRIPTION
**         Output          - Set LED status (ON/OFF) accordant
**                           with the 'Output' value
**                           <true> - Turn the LED ON
**                           <false> - Turn the LED OFF
**     Returns     : Nothing
** ===================================================================
*/

bool LED_Act_Status(void);
#define LED_Act_Status() Inhr1_GetVal()
/*
** ===================================================================
**     Method      :  LED_Act_Status (component DSC_LED)
**     Description :
**         Return the last written value of the LED device
**     Parameters  : None
**     Returns     :
**         ---             - The last written value of the LED device.
**                           <true> - The LED is ON
**                           <false> - The LED is OFF
** ===================================================================
*/

#define LED_Act_ConnectPin Inhr1_ConnectPin
/*
** ===================================================================
**     Method      :  LED_Act_ConnectPin (component DSC_LED)
**     Description :
**         This method reconnects selected pin in this bean. This
**         method is available only for CPU derivatives and peripherals
**         that support runtime pin sharing with other internal on-chip
**         peripherals.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

/* END LED_Act. */

#endif /* ifndef __LED_Act */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
