/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : ADC0.h
**     Project     : Control_Intensidad_ADC_PWM_PDB
**     Processor   : MC56F8006_48_LQFP
**     Component   : Init_ADC
**     Version     : Component 01.350, Driver 01.01, CPU db: 3.00.209
**     Compiler    : CodeWarrior DSP C Compiler
**     Date/Time   : 2014-08-26, 12:03, # CodeGen: 16
**     Abstract    :
**         This "Init_ADC" Peripheral Inspector implements the
**         Analog-to-Digital converter module (ADC), basic 
**         initialization and settings.
**     Settings    :
**          Component name                                 : ADC0
**          Device                                         : ADC0
**          Settings                                       : 
**            Clock settings                               : 
**              Input clock                                : Bus clock
**              Continuous clock output                    : Inactived
**              Clock divide select                        : Input clock / 4
**              Sample time                                : Short
**              ADCK frequency                             : 8 MHz
**              Conversion time                            : 3.03 us
**            Continuous conversion A                      : Disabled
**            Continuous conversion B                      : Disabled
**            Conversion mode                              : 10-bit
**            Power configuration                          : High speed
**            Conversion trigger                           : Hardware
**            Voltage reference                            : VDDA/VSSA
**          Pins/Signals                                   : 
**            ADC input pins                               : 1
**              Input pin 0                                : 
**                Pin                                      : GPIOC0_ANA5_FAULT0_CMP1_M1
**                Pin signal                               : 
**          Interrupts/DMA                                 : 
**            Conversion complete                          : 
**              Interrupt                                  : INT_ADC0_Complete
**              Interrupt priority                         : medium priority
**              Conversion A complete                      : Enabled interrupt
**              Conversion B complete                      : Disabled interrupt
**              ISR name                                   : INT_ADC0_Complete
**          Initialization                                 : 
**            Call Init method                             : yes
**            Enable peripheral clock                      : yes
**            Initial channel A select                     : Disabled
**            Initial channel B select                     : Disabled
**     Contents    :
**         Init - void ADC0_Init(void);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file ADC0.h
** @version 01.01
** @brief
**         This "Init_ADC" Peripheral Inspector implements the
**         Analog-to-Digital converter module (ADC), basic 
**         initialization and settings.
*/         
/*!
**  @addtogroup ADC0_module ADC0 module documentation
**  @{
*/         

#ifndef __ADC0_H
#define __ADC0_H

/* MODULE ADC0. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */

#include "Cpu.h"




/* PESL device mapping  */
#define ADC0_DEVICE ADC0

extern void INT_ADC0_Complete(void);

void ADC0_Init(void);
/*
** ===================================================================
**     Method      :  ADC0_Init (component Init_ADC)
**     Description :
**         This method initializes registers of the ADC module
**         according to this Peripheral Initialization settings. Call
**         this method in the user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

/* END ADC0. */

#endif
/* ifndef __ADC0_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
