/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : PWMC1.c
**     Project     : Control_Intensidad_ADC_PWM_PDB
**     Processor   : MC56F8006_48_LQFP
**     Component   : PWMMC
**     Version     : Component 01.779, Driver 01.32, CPU db: 3.00.209
**     Compiler    : CodeWarrior DSP C Compiler
**     Date/Time   : 2014-08-26, 12:03, # CodeGen: 16
**     Abstract    :
**         This component "PWMMC" implements 6-channel center-aligned or 
**         edge-aligned pulse-width modulator for AC motor control, which 
**         is presented on chip. The device is capable of controlling most 
**         motor types: AC induction motors (ACIM), both brushless (BLDC) 
**         and brush DC motors (BDC), switched (SRM) and variable reluctance  
**         motors (VRM),and stepper motors.
**         Another possibility of using this component is as a pulse-width modulation 
**         generator that generates 6 signals with variable duty and fixed cycle.
**     Settings    :
**          Component name                                 : PWMC1
**          Device                                         : PWM_Timer
**          Align                                          : center-aligned mode
**          Mode of PWM Pair 0                             : independent
**          Mode of PWM Pair 1                             : independent
**          Mode of PWM Pair 2                             : independent
**          Top-Side PWM Pair 0 Polarity                   : Positive
**          Top-Side PWM Pair 1 Polarity                   : Positive
**          Top-Side PWM Pair 2 Polarity                   : Positive
**          Bottom-Side PWM Pair 0 Polarity                : Positive
**          Bottom-Side PWM Pair 1 Polarity                : Positive
**          Bottom-Side PWM Pair 2 Polarity                : Positive
**          Write Protect                                  : no
**          Output pads                                    : Disabled
**          Synchronization output                         : Disabled
**          Synchronization window                         : Disabled
**          Enable in Wait mode                            : no
**          Enable in EnOnCE mode                          : yes
**          Reload                                         : 1
**          Half cycle reload                              : no
**          Hardware acceleration                          : Disabled
**          Frequency/period                               : 100 kHz
**          Output Frequency                               : 50 kHz
**          Same frequency in modes                        : no
**          Dead-time                                      : 0 µs
**          Dead-time 1                                    : 0 µs
**          Correction                                     : Disabled
**          Interrupt service/event                        : Disabled
**          Channel 0                                      : 
**            Channel                                      : PWMod0
**            PWM pin                                      : GPIOA0_PWM0
**            PWM pin signal                               : 
**            Duty                                         : 50 %
**            Pin PWM0 active                              : no
**            Output software control                      : no
**            PWM compare invert                           : no
**            Mask channel                                 : no
**            Mask fault 0                                 : PWM unaffected
**            Mask fault 1                                 : PWM unaffected
**            Mask fault 2                                 : PWM unaffected
**            Mask fault 3                                 : PWM unaffected
**          Channel 1                                      : Disabled
**          Channel 2                                      : Disabled
**          Channel 3                                      : Disabled
**          Channel 4                                      : Disabled
**          Channel 5                                      : Disabled
**          Fault protection                               : controlled by this component
**            Fault 0                                      : Disabled
**            Fault 1                                      : Disabled
**            Fault 2                                      : Disabled
**            Fault 3                                      : Disabled
**          Initialization                                 : 
**            Enabled in init. code                        : yes
**            Events enabled in init.                      : yes
**          CPU clock/speed selection                      : 
**            High speed mode                              : This component enabled
**            Low speed mode                               : This component disabled
**            Slow speed mode                              : This component disabled
**          Simulation output mode                         : PWM
**          High output value                              : 1
**          Low output value                               : 0
**     Contents    :
**         Enable           - byte PWMC1_Enable(void);
**         Disable          - byte PWMC1_Disable(void);
**         SetDuty          - byte PWMC1_SetDuty(byte Channel, PWMC1_TPWMMC_Duty Duty);
**         Load             - void PWMC1_Load(void);
**         OutputPadEnable  - void PWMC1_OutputPadEnable(void);
**         OutputPadDisable - void PWMC1_OutputPadDisable(void);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file PWMC1.c
** @version 01.32
** @brief
**         This component "PWMMC" implements 6-channel center-aligned or 
**         edge-aligned pulse-width modulator for AC motor control, which 
**         is presented on chip. The device is capable of controlling most 
**         motor types: AC induction motors (ACIM), both brushless (BLDC) 
**         and brush DC motors (BDC), switched (SRM) and variable reluctance  
**         motors (VRM),and stepper motors.
**         Another possibility of using this component is as a pulse-width modulation 
**         generator that generates 6 signals with variable duty and fixed cycle.
*/         
/*!
**  @addtogroup PWMC1_module PWMC1 module documentation
**  @{
*/         


/* MODULE PWMC1. */

#include "PWMC1.h"

static bool EnUser;                    /* Enable/Disable device by user */

/*
** ===================================================================
**     Method      :  PWMC1_HWEnDi (component PWMMC)
**
**     Description :
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void HWEnDi(void)
{
  if (EnUser) {                        /* Enable device? */
    setRegBits(PWM_CTRL,0x02);         /* Load counter and modulo registers into buffers */
    setRegBits(PWM_CTRL,0x01);         /* Run counter*/
    clrRegBits(PWM_CTRL,0x10);         /* Clear reload flag made by PWMEN bit */
  }
  else {                               /* Disable device? */
    clrRegBits(PWM_CTRL,0x01);         /* Stop counter */
  }
}
/*
** ===================================================================
**     Method      :  PWMC1_Enable (component PWMMC)
**     Description :
**         Enable the component - it starts the signal generation.
**         Events can be disabled/enabled by <DisableEvent>
**         /<EnableEvent>.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte PWMC1_Enable(void)
{
  if (!EnUser) {                       /* Is the device disabled by user? */
    EnUser = TRUE;                     /* If yes then set the flag "device enabled" */
    HWEnDi();                          /* Enable the device */
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  PWMC1_Disable (component PWMMC)
**     Description :
**         Disable the component - it stops signal generation and
**         events calling. When the timer is disabled, it is still
**         possible to call method <SetOutput> to control the output
**         value on corresponding pin.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte PWMC1_Disable(void)
{
  if (EnUser) {                        /* Is the device enabled by user? */
    EnUser = FALSE;                    /* If yes then set the flag "device disabled" */
    HWEnDi();                          /* Disable the device */
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  PWMC1_Init (component PWMMC)
**
**     Description :
**         Initializes the associated peripheral(s) and the bean internal 
**         variables. The method is called automatically as a part of the 
**         application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void PWMC1_Init(void)
{
  /* PWM_CTRL: LDFQ=0,HALF=0,IPOL2=0,IPOL1=0,IPOL0=0,PRSC=0,PWMRIE=0,PWMF=0,??=0,??=0,LDOK=0,PWMEN=0 */
  setReg16(PWM_CTRL, 0x00U);           /* Set up PWM control register */ 
  /* PWM_FCTRL: ??=0,??=0,??=0,??=0,FPOL3=0,FPOL2=0,FPOL1=0,FPOL0=0,FIE3=0,FMODE3=0,FIE2=0,FMODE2=0,FIE1=0,FMODE1=0,FIE0=0,FMODE0=0 */
  setReg16(PWM_FCTRL, 0x00U);          /* Set up Fault Control Register */ 
  /* PWM_ICCTRL: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,PEC2=0,PEC1=0,PEC0=0,ICC2=0,ICC1=0,ICC0=0 */
  setReg16(PWM_ICCTRL, 0x00U);         /* Set up Internal Correction Control Register */ 
  /* PWM_DMAP1: DISMAP_15_0=0 */
  setReg16(PWM_DMAP1, 0x00U);           
  /* PWM_DMAP2: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,DISMAP_23_16=0 */
  setReg16(PWM_DMAP2, 0x00U);           
  /* PWM_OUT: PAD_EN=0,??=0,OUTCTL5=0,OUTCTL4=0,OUTCTL3=0,OUTCTL2=0,OUTCTL1=0,OUTCTL0=0,??=0,??=0,OUT5=0,OUT4=0,OUT3=0,OUT2=0,OUT1=0,OUT0=0 */
  setReg16(PWM_OUT, 0x00U);             
  /* PWM_CCTRL: ENHA=0,nBX=0,MSK5=0,MSK4=0,MSK3=0,MSK2=0,MSK1=0,MSK0=0,??=0,??=0,VLMODE=0,??=0,SWP45=0,SWP23=0,SWP01=0 */
  setReg16(PWM_CCTRL, 0x00U);           
  /* PWM_SCTRL: ??=0,??=0,CINV5=0,CINV4=0,CINV3=0,CINV2=0,CINV1=0,CINV0=0,??=0,SRC2=0,??=0,SRC1=0,??=0,SRC0=0 */
  setReg16(PWM_SCTRL, 0x00U);           
  /* PWM_FFILT0: GSTR0=0,??=0,??=0,??=0,??=0,FILT0_CNT=0,FILT0_PER=0 */
  setReg16(PWM_FFILT0, 0x00U);          
  /* PWM_FFILT1: GSTR1=0,??=0,??=0,??=0,??=0,FILT1_CNT=0,FILT1_PER=0 */
  setReg16(PWM_FFILT1, 0x00U);          
  /* PWM_FFILT2: GSTR2=0,??=0,??=0,??=0,??=0,FILT2_CNT=0,FILT2_PER=0 */
  setReg16(PWM_FFILT2, 0x00U);          
  /* PWM_FFILT3: GSTR3=0,??=0,??=0,??=0,??=0,FILT3_CNT=0,FILT3_PER=0 */
  setReg16(PWM_FFILT3, 0x00U);          
  /* PWM_DTIM0: ??=0,??=0,??=0,??=0,PWMDT0=0 */
  setReg16(PWM_DTIM0, 0x00U);           
  /* PWM_DTIM1: ??=0,??=0,??=0,??=0,PWMDT1=0 */
  setReg16(PWM_DTIM1, 0x00U);           
  /* PWM_VAL0: PMVAL=0x01E0 */
  setReg16(PWM_VAL0, 0x01E0U);          
  /* PWM_CMOD: ??=0,PWMCM=0x03C0 */
  setReg16(PWM_CMOD, 0x03C0U);          
  /* PWM_CNFG: ??=0,DBG_EN=1,WAIT_EN=0,EDG=0,??=0,TOPNEG45=0,TOPNEG23=0,TOPNEG01=0,??=0,BOTNEG45=0,BOTNEG23=0,BOTNEG01=0,INDEP45=0,INDEP23=0,INDEP01=1,WP=0 */
  setReg16(PWM_CNFG, 0x4002U);         /* Set up PWM configure register */ 
  EnUser = TRUE;                       /* Enable device */
  HWEnDi();                            /* Enable/disable device according to status flags */

}

/*
** ===================================================================
**     Method      :  PWMC1_SetDuty (component PWMMC)
**     Description :
**         Setting duty (value) register(s) of selected channel. The
**         value is loaded after calling <Load> method.
**         
**         [ Version specific information for Freescale 56800/E and
**         HC08 and HCS12 and HCS12X derivatives ] 
**         Setting is valid for actual speed mode only, initial value
**         is restored after speed mode change.
**         
**         [ Version specific information for Freescale 56800/E
**         derivatives - eFlexPWM device ] 
**         Duty register(s) value is not affected during speed mode
**         change. It should be handled by the user code.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Channel         - Channel number (0 - 5). The number
**                           corresponds to the logical channel number
**                           assigned in the component settings, which
**                           may not correspond to channel number of the
**                           peripheral.
**         Duty            - Duty value for selected channel.
**                           
**                           Writing a number less than or equal to 0
**                           causes the PWM to be off for the entire PWM
**                           period. Writing a number greater than or
**                           equal to the 15 bit (12-bit on HC08MR32 CPU)
**                           modulus causes the PWM to be on for the
**                           entire PWM period.
**                           
**                           [ Version specific information for
**                           Freescale 56800/E derivatives - eFlexPWM
**                           device ] 
**                           Parameter duty is an unsigned value. 
**                           - _edge-aligned mode:_ parameter value is
**                           written into PWM clear-edge
**                           (eFlexPWM_SMn_VALx) register; PWM set-edge
**                           (eFlexPWM_SMn_VALx) register is not
**                           affected (zero value assumed); where x = 2,
**                           4. 
**                           - _center-aligned mode:_ parameter value is
**                           split between PWM set-edge
**                           (eFlexPWM_SMn_VALx) and PWM clear-edge
**                           (eFlexPWM_SMn_VAL(x+1)) registers; where x
**                           = 2, 4.
**     Returns     :
**         ---             - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_NOTAVAIL - Channel is disabled 
**                           - ERR_RANGE - Parameter Channel is out of
**                           range
** ===================================================================
*/
byte PWMC1_SetDuty(byte Channel,PWMC1_TPWMMC_Duty Duty)
{
  switch (Channel) {
  case 0 :
      setReg(PWM_VAL0,Duty);           /* Store value to the duty-compare register 0 */
      break;
  case 1 :
     return ERR_NOTAVAIL;
  case 2 :
      return ERR_NOTAVAIL;
  case 3 :
      return ERR_NOTAVAIL;
  case 4 :
      return ERR_NOTAVAIL;
  case 5 :
      return ERR_NOTAVAIL;
  default: return ERR_RANGE;
  }
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  PWMC1_Load (component PWMMC)
**     Description :
**         Apply last setting of the methods <SetDuty>, <SetDutyPercent>,
**         both <SetRatio*>, <SetPeriod> and <SetPrescaler>.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void PWMC1_Load(void)

**  This method is implemented as a macro. See PWMC1.h file.  **

*/

/*
** ===================================================================
**     Method      :  PWMC1_OutputPadEnable (component PWMMC)
**     Description :
**         Method enables output pads.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void PWMC1_OutputPadEnable(void)

**  This method is implemented as a macro. See PWMC1.h file.  **

*/

/*
** ===================================================================
**     Method      :  PWMC1_OutputPadDisable (component PWMMC)
**     Description :
**         Method disables output pads.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void PWMC1_OutputPadDisable(void)

**  This method is implemented as a macro. See PWMC1.h file.  **

*/

/* END PWMC1. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
